/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function transformSync(s: string, isModule: boolean, opts: Buffer): TransformOutput;
export interface TransformOutput {
  code: string;
  map?: string;
}
export function swcTransformSync(s: string, isModule: boolean, opts: Buffer): TransformOutput;
