/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface TransformOutput {
  code: string;
  map?: string;
}
export function minifySync(code: Buffer, opts: Buffer): TransformOutput;
export interface TransformerCustomOptions {
  externalPackages: Array<string>;
}
export interface Metadata {
  requires: Array<string>;
}
export interface TransformOutput {
  code: string;
  map?: string;
  metadata: Metadata;
}
export function transformSync(s: string, opts: Buffer, customOpts?: Buffer | undefined | null): TransformOutput;
